### ISSUE TITLE
create a UI for eCommerce system for photocopy shop at college campus

### ISSUE THREAD

**Issue by ruchikapatro24** [SnowScriptWinterOfCode/UI-UX-Case-Studies#18]

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by ruchikapatro24** [comment]
@Nitya-Pasrija please assign it to me

**Comment by ruchikapatro24** [comment]
@captain-sal @Nitya-Pasrija please assign me this
