### ISSUE TITLE
UI UX for an astronomical clone of netflix 

### ISSUE THREAD

**Issue by ANSHIKA-26** [SnowScriptWinterOfCode/UI-UX-Case-Studies#8]

**Comment by ANSHIKA-26** [comment]
please assign this issue to me @Nitya-Pasrija

**Comment by Manvi1718** [comment]
hii , actually i have already made a beautiful UI/UX for astronomical clone of Netflix . please assign this issue to me .

**Comment by Nitya-Pasrija** [comment]
Closing this as complete
@ANSHIKA-26 do take care to mention the issue number (#issue_nuber) in your PR

**Comment by ANSHIKA-26** [comment]
> Closing this as complete @ANSHIKA-26 do take care to mention the issue number (#issue_nuber) in your PR

sure will do ! thank you so much
